### ISSUE TITLE
Injecting javascript not working

### ISSUE THREAD

**Issue by euclides-jr** [ammarahm-ed/react-native-geckoview#3]
Hi there, I set up the projected, and copied the messaging extension and it seems to work but the only message a I get is "hello world" no matter what I set in the `injectedJavaScript` prop. I believe the "hello world" message is coming from the extension here https://github.com/ammarahm-ed/react-native-geckoview/blob/main/extensions/messaging/content.js#L25 and the code injection / messaging is not working.

**Comment by ammarahm-ed** [comment]
@euclides-jr I just fixed it. try 1.4.0. make sure to copy the extension again to assets folder.
